### ISSUE TITLE
Unexpected end of JSON output

### ISSUE THREAD

**Issue by Ilovegym66** [DNAngelX/ioBroker.notificationforandroidtv#6]
Admin V6.13.15, Js-controller 5.0.17, Node 18.19.1, buanet-docker V9.0.1, same with Raspi-4 on Bookworm with Node 20, start of the adapter not possible any more:

`
2024-01-09 14:22:26.123  - info: puppeteer.0 (1466) Ready to take screenshots
2024-01-09 14:30:42.008  - info: host.testbroker iobroker url https://github.com/DNAngelX/ioBroker.notificationforandroidtv.git --host testbroker --debug
2024-01-09 14:30:42.008  - info: host.testbroker iobroker url https://github.com/DNAngelX/ioBroker.notificationforandroidtv.git --host testbroker --debug
2024-01-09 14:30:48.326  - info: host.testbroker iobroker install DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d
2024-01-09 14:30:48.913  - info: host.testbroker iobroker NPM version: 10.2.3Installing DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d... (System call)
2024-01-09 14:30:48.326  - info: host.testbroker iobroker install DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d
2024-01-09 14:30:48.913  - info: host.testbroker iobroker NPM version: 10.2.3Installing DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d... (System call)
2024-01-09 14:30:51.034  - info: host.testbroker iobroker npm WARN skipping integrity check for git dependency ssh://git@github.com/DNAngelX/ioBroker.notificationforandroidtv.git
2024-01-09 14:30:51.526  - info: host.testbroker iobroker added 1 package in 2s
2024-01-09 14:30:51.527  - info: host.testbroker iobroker
2024-01-09 14:30:51.528  - info: host.testbroker iobroker 34 packages are looking for funding
2024-01-09 14:30:51.529  - info: host.testbroker iobroker   run `npm fund` for details
2024-01-09 14:30:51.034  - info: host.testbroker iobroker npm WARN skipping integrity check for git dependency ssh://git@github.com/DNAngelX/ioBroker.notificationforandroidtv.git
2024-01-09 14:30:51.526  - info: host.testbroker iobroker added 1 package in 2s
2024-01-09 14:30:51.527  - info: host.testbroker iobroker
2024-01-09 14:30:51.528  - info: host.testbroker iobroker 34 packages are looking for funding
2024-01-09 14:30:51.529  - info: host.testbroker iobroker   run `npm fund` for details
2024-01-09 14:30:57.588  - info: host.testbroker iobroker upload [3] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/index_m.html index_m.html text/html
2024-01-09 14:30:57.635  - info: host.testbroker iobroker upload [2] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/notificationforandroidtv.png notificationforandroidtv.png image/png
2024-01-09 14:30:57.661  - info: host.testbroker iobroker upload [1] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/style.css style.css text/css
2024-01-09 14:30:57.687  - info: host.testbroker iobroker upload [0] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/words.js words.js application/javascript
2024-01-09 14:30:57.760  - info: host.testbroker iobroker Update "system.adapter.notificationforandroidtv.0"
2024-01-09 14:30:57.588  - info: host.testbroker iobroker upload [3] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/index_m.html index_m.html text/html
2024-01-09 14:30:57.635  - info: host.testbroker iobroker upload [2] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/notificationforandroidtv.png notificationforandroidtv.png image/png
2024-01-09 14:30:57.661  - info: host.testbroker iobroker upload [1] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/style.css style.css text/css
2024-01-09 14:30:57.687  - info: host.testbroker iobroker upload [0] notificationforandroidtv.admin /opt/iobroker/node_modules/iobroker.notificationforandroidtv/admin/words.js words.js application/javascript
2024-01-09 14:30:57.760  - info: host.testbroker iobroker Update "system.adapter.notificationforandroidtv.0"
2024-01-09 14:30:58.797  - info: host.testbroker iobroker exit 0
2024-01-09 14:30:58.797  - info: host.testbroker iobroker exit 0
2024-01-09 14:31:39.323  - info: host.testbroker "system.adapter.notificationforandroidtv.0" enabled
2024-01-09 14:31:39.472  - info: host.testbroker instance system.adapter.notificationforandroidtv.0 started with pid 4952
2024-01-09 14:31:39.323  - info: host.testbroker "system.adapter.notificationforandroidtv.0" enabled
2024-01-09 14:31:39.472  - info: host.testbroker instance system.adapter.notificationforandroidtv.0 started with pid 4952
2024-01-09 14:31:41.238  - info: notificationforandroidtv.0 (4952) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:31:41.252  - error: notificationforandroidtv.0 (4952) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:31:41.257  - error: notificationforandroidtv.0 (4952) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:31:41.257  - error: notificationforandroidtv.0 (4952) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.257  - error: notificationforandroidtv.0 (4952) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:31:41.258  - error: notificationforandroidtv.0 (4952) Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.252  - error: notificationforandroidtv.0 (4952) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.255  - error: notificationforandroidtv.0 (4952) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:31:41.256  - error: notificationforandroidtv.0 (4952) Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.256  - info: notificationforandroidtv.0 (4952) registerNotification not processed because States database not connected
2024-01-09 14:31:41.280  - info: notificationforandroidtv.0 (4952) terminating
2024-01-09 14:31:41.280  - warn: notificationforandroidtv.0 (4952) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:31:41.419  - error: notificationforandroidtv.0 (4952) notificationforandroidtv.0 already running
2024-01-09 14:31:41.420  - warn: notificationforandroidtv.0 (4952) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2024-01-09 14:31:41.759  - info: notificationforandroidtv.0 (4952) terminating
2024-01-09 14:31:41.781  - info: notificationforandroidtv.0 (4952) terminating
2024-01-09 14:31:41.907  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 14:31:41.907  - info: host.testbroker Restart adapter system.adapter.notificationforandroidtv.0 because enabled
2024-01-09 14:31:41.238  - info: notificationforandroidtv.0 (4952) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:31:41.252  - error: notificationforandroidtv.0 (4952) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:31:41.257  - error: notificationforandroidtv.0 (4952) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:31:41.257  - error: notificationforandroidtv.0 (4952) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.257  - error: notificationforandroidtv.0 (4952) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:31:41.258  - error: notificationforandroidtv.0 (4952) Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.252  - error: notificationforandroidtv.0 (4952) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.255  - error: notificationforandroidtv.0 (4952) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:31:41.256  - error: notificationforandroidtv.0 (4952) Cannot read properties of undefined (reading 'error')
2024-01-09 14:31:41.256  - info: notificationforandroidtv.0 (4952) registerNotification not processed because States database not connected
2024-01-09 14:31:41.280  - info: notificationforandroidtv.0 (4952) terminating
2024-01-09 14:31:41.280  - warn: notificationforandroidtv.0 (4952) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:31:41.419  - error: notificationforandroidtv.0 (4952) notificationforandroidtv.0 already running
2024-01-09 14:31:41.420  - warn: notificationforandroidtv.0 (4952) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2024-01-09 14:31:41.759  - info: notificationforandroidtv.0 (4952) terminating
2024-01-09 14:31:41.781  - info: notificationforandroidtv.0 (4952) terminating
2024-01-09 14:31:41.907  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 14:31:41.907  - info: host.testbroker Restart adapter system.adapter.notificationforandroidtv.0 because enabled
2024-01-09 14:31:51.796  - info: host.testbroker "system.adapter.notificationforandroidtv.0" disabled
2024-01-09 14:31:51.796  - info: host.testbroker "system.adapter.notificationforandroidtv.0" disabled
2024-01-09 14:32:14.168  - error: notificationforandroidtv.0 (5167) adapter disabled
2024-01-09 14:32:14.187  - warn: notificationforandroidtv.0 (5167) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
2024-01-09 14:32:14.168  - error: notificationforandroidtv.0 (5167) adapter disabled
2024-01-09 14:32:14.187  - warn: notificationforandroidtv.0 (5167) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
2024-01-09 14:32:14.818  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
2024-01-09 14:32:14.831  - info: host.testbroker Do not restart adapter system.adapter.notificationforandroidtv.0 because disabled or deleted
2024-01-09 14:32:14.818  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
2024-01-09 14:32:14.831  - info: host.testbroker Do not restart adapter system.adapter.notificationforandroidtv.0 because disabled or deleted
2024-01-09 14:32:55.067  - info: host.testbroker "system.adapter.notificationforandroidtv.0" enabled
2024-01-09 14:32:55.164  - info: host.testbroker instance system.adapter.notificationforandroidtv.0 started with pid 5433
2024-01-09 14:32:55.067  - info: host.testbroker "system.adapter.notificationforandroidtv.0" enabled
2024-01-09 14:32:55.164  - info: host.testbroker instance system.adapter.notificationforandroidtv.0 started with pid 5433
2024-01-09 14:32:57.362  - info: notificationforandroidtv.0 (5433) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:32:57.556  - info: notificationforandroidtv.0 (5433) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:32:57.984  - error: notificationforandroidtv.0 (5433) uncaught exception: Unexpected end of JSON input
2024-01-09 14:32:57.993  - error: notificationforandroidtv.0 (5433) uncaught exception: Unexpected end of JSON input
2024-01-09 14:32:57.992  - error: notificationforandroidtv.0 (5433) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Notificationforandroidtv.onStateChange (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:382:21)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8516:53)
    at process.processImmediate (node:internal/timers:478:21)
2024-01-09 14:32:57.993  - error: notificationforandroidtv.0 (5433) Unexpected end of JSON input
2024-01-09 14:32:57.993  - error: notificationforandroidtv.0 (5433) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Notificationforandroidtv.onStateChange (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:382:21)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8516:53)
    at process.processImmediate (node:internal/timers:478:21)
2024-01-09 14:32:57.994  - error: notificationforandroidtv.0 (5433) Unexpected end of JSON input
2024-01-09 14:32:58.000  - info: notificationforandroidtv.0 (5433) terminating
2024-01-09 14:32:58.001  - warn: notificationforandroidtv.0 (5433) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:32:58.500  - info: notificationforandroidtv.0 (5433) terminating
2024-01-09 14:32:58.501  - warn: notificationforandroidtv.0 (5433) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:32:58.502  - info: notificationforandroidtv.0 (5433) terminating
2024-01-09 14:32:58.524  - error: notificationforandroidtv.0 (5433) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:32:58.531  - error: notificationforandroidtv.0 (5433) unhandled promise rejection: Connection is closed.
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:337:12)
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Connection is closed.
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) unhandled promise rejection: Connection is closed.
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:337:12)
2024-01-09 14:32:58.533  - error: notificationforandroidtv.0 (5433) Connection is closed.
2024-01-09 14:32:58.609  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 14:32:58.609  - info: host.testbroker Restart adapter system.adapter.notificationforandroidtv.0 because enabled
2024-01-09 14:32:57.362  - info: notificationforandroidtv.0 (5433) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:32:57.556  - info: notificationforandroidtv.0 (5433) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:32:57.984  - error: notificationforandroidtv.0 (5433) uncaught exception: Unexpected end of JSON input
2024-01-09 14:32:57.993  - error: notificationforandroidtv.0 (5433) uncaught exception: Unexpected end of JSON input
2024-01-09 14:32:57.992  - error: notificationforandroidtv.0 (5433) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Notificationforandroidtv.onStateChange (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:382:21)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8516:53)
    at process.processImmediate (node:internal/timers:478:21)
2024-01-09 14:32:57.993  - error: notificationforandroidtv.0 (5433) Unexpected end of JSON input
2024-01-09 14:32:57.993  - error: notificationforandroidtv.0 (5433) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Notificationforandroidtv.onStateChange (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:382:21)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8516:53)
    at process.processImmediate (node:internal/timers:478:21)
2024-01-09 14:32:57.994  - error: notificationforandroidtv.0 (5433) Unexpected end of JSON input
2024-01-09 14:32:58.000  - info: notificationforandroidtv.0 (5433) terminating
2024-01-09 14:32:58.001  - warn: notificationforandroidtv.0 (5433) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:32:58.500  - info: notificationforandroidtv.0 (5433) terminating
2024-01-09 14:32:58.501  - warn: notificationforandroidtv.0 (5433) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:32:58.502  - info: notificationforandroidtv.0 (5433) terminating
2024-01-09 14:32:58.524  - error: notificationforandroidtv.0 (5433) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:32:58.531  - error: notificationforandroidtv.0 (5433) unhandled promise rejection: Connection is closed.
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:337:12)
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Connection is closed.
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) unhandled promise rejection: Connection is closed.
2024-01-09 14:32:58.532  - error: notificationforandroidtv.0 (5433) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:337:12)
2024-01-09 14:32:58.533  - error: notificationforandroidtv.0 (5433) Connection is closed.
2024-01-09 14:32:58.609  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 14:32:58.609  - info: host.testbroker Restart adapter system.adapter.notificationforandroidtv.0 because enabled
2024-01-09 14:33:28.698  - info: host.testbroker instance system.adapter.notificationforandroidtv.0 started with pid 5654
2024-01-09 14:33:28.698  - info: host.testbroker instance system.adapter.notificationforandroidtv.0 started with pid 5654
2024-01-09 14:33:30.709  - info: notificationforandroidtv.0 (5654) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:33:30.723  - error: notificationforandroidtv.0 (5654) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:33:30.727  - error: notificationforandroidtv.0 (5654) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:33:30.729  - error: notificationforandroidtv.0 (5654) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.729  - error: notificationforandroidtv.0 (5654) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:33:30.730  - error: notificationforandroidtv.0 (5654) Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.724  - error: notificationforandroidtv.0 (5654) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.726  - error: notificationforandroidtv.0 (5654) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:33:30.726  - error: notificationforandroidtv.0 (5654) Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.727  - info: notificationforandroidtv.0 (5654) registerNotification not processed because States database not connected
2024-01-09 14:33:30.737  - info: notificationforandroidtv.0 (5654) terminating
2024-01-09 14:33:30.738  - warn: notificationforandroidtv.0 (5654) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:33:31.194  - error: notificationforandroidtv.0 (5654) notificationforandroidtv.0 already running
2024-01-09 14:33:31.195  - warn: notificationforandroidtv.0 (5654) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2024-01-09 14:33:31.233  - info: notificationforandroidtv.0 (5654) terminating
2024-01-09 14:33:31.238  - info: notificationforandroidtv.0 (5654) terminating
2024-01-09 14:33:31.371  - error: host.testbroker instance system.adapter.notificationforandroidtv.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 14:33:31.371  - info: host.testbroker Restart adapter system.adapter.notificationforandroidtv.0 because enabled
2024-01-09 14:33:31.371  - warn: host.testbroker Do not restart adapter system.adapter.notificationforandroidtv.0 because restart loop detected
2024-01-09 14:33:30.709  - info: notificationforandroidtv.0 (5654) starting. Version 2.3.0 (non-npm: DNAngelX/ioBroker.notificationforandroidtv#d9fc47833dbc17e1a499494050b2df31bf7ec23d) in /opt/iobroker/node_modules/iobroker.notificationforandroidtv, node: v20.10.0, js-controller: 5.0.17
2024-01-09 14:33:30.723  - error: notificationforandroidtv.0 (5654) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:33:30.727  - error: notificationforandroidtv.0 (5654) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 14:33:30.729  - error: notificationforandroidtv.0 (5654) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.729  - error: notificationforandroidtv.0 (5654) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:33:30.730  - error: notificationforandroidtv.0 (5654) Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.724  - error: notificationforandroidtv.0 (5654) unhandled promise rejection: Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.726  - error: notificationforandroidtv.0 (5654) TypeError: Cannot read properties of undefined (reading 'error')
    at Notificationforandroidtv.onReady (/opt/iobroker/node_modules/iobroker.notificationforandroidtv/main.js:338:22)
    at Notificationforandroidtv.emit (node:events:514:28)
    at Notificationforandroidtv._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9118:18)
    at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9097:26
2024-01-09 14:33:30.726  - error: notificationforandroidtv.0 (5654) Cannot read properties of undefined (reading 'error')
2024-01-09 14:33:30.727  - info: notificationforandroidtv.0 (5654) registerNotification not processed because States database not connected
2024-01-09 14:33:30.737  - info: notificationforandroidtv.0 (5654) terminating
2024-01-09 14:33:30.738  - warn: notificationforandroidtv.0 (5654) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 14:33:31.194  - error: notificationforandroidtv.0 (5654) notificationforandroidtv.0 already running
2024-01-09 14:33:31.195  - warn: notificationforandroidtv.0 (5654) Terminated (ADAPTER_ALREADY_RUNNING): Without reason

`

**Comment by DNAngelX** [comment]
Ist behoben, bekommen den nur nicht  zu IoBroker:

Add ioBroker.notificationforandroidtv to beta/latest repository
Connecting to GitHub...
Connected to GitHub as DNAngelX
Found fork DNAngelX/ioBroker.repositories
Cloning repository from GitHub
Creating branch notificationforandroidtv-to-latest
Preparing ioBroker.repositories (this may take a while)
Adding notificationforandroidtv to latest locally
Pushing changes to DNAngelX/ioBroker.repositories
Error: Process exited with 1
Failed
